<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
        	[
		    	'permission_title' => 'Escritorio',
		    	'permission_slug' => 'App\Http\Controllers\Admin\DashboardController@index',
		    	'permission_description'=>'Escritorio',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Perfil ver',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@index', 
		    	'permission_description'=>'Perfil ver',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Perfil editar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@edit', 
		    	'permission_description'=>'Perfil editar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Perfil actualizar información',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@updateInfo', 
		    	'permission_description'=>'Perfil actualizar información',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Perfil actualizar seguridad',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@updateSecurity', 
		    	'permission_description'=>'Perfil actualizar seguridad',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Perfil editar avatar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@editAvatar', 
		    	'permission_description'=>'Perfil editar avatar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Perfil actualizar avatar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@updateAvatar', 
		    	'permission_description'=>'Perfil actualizar avatar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Perfil confirmar email',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@confirmEmailRegistration', 
		    	'permission_description'=>'Perfil confirmar email',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
		    [
		    	'permission_title' => 'Roles index',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@index', 
		    	'permission_description'=>'Roles index',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Roles',
		    	'menu_module_icon'=>'fa-user',
		    	'menu_item'=>'Mostrar',
		    	'menu_item_route'=>'admin.roles.index',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Roles crear',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@create', 
		    	'permission_description'=>'Roles crear',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Roles',
		    	'menu_module_icon'=>'fa-user',
		    	'menu_item'=>'Crear',
		    	'menu_item_route'=>'admin.roles.create',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Roles guardar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@store', 
		    	'permission_description'=>'Roles guardar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Roles listar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@show', 
		    	'permission_description'=>'Roles listar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Roles editar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@edit', 
		    	'permission_description'=>'Roles editar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Roles actualizar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@update', 
		    	'permission_description'=>'Roles actualizar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Roles eliminar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@destroy', 
		    	'permission_description'=>'Roles eliminar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Permisos index',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@index', 
		    	'permission_description'=>'Permisos index',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Permisos',
		    	'menu_module_icon'=>'fa-lock',
		    	'menu_item'=>'Mostrar',
		    	'menu_item_route'=>'admin.permissions.index',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Permisos crear',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@create', 
		    	'permission_description'=>'Permisos crear',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Permisos',
		    	'menu_module_icon'=>'fa-lock',
		    	'menu_item'=>'Crear',
		    	'menu_item_route'=>'admin.permissions.create',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Permisos guardar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@store', 
		    	'permission_description'=>'Permisos guardar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Permisos listar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@show', 
		    	'permission_description'=>'Permisos listar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Permisos editar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@edit', 
		    	'permission_description'=>'Permisos editar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Permisos actualizar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@update', 
		    	'permission_description'=>'Permisos actualizar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Permisos eliminar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@destroy', 
		    	'permission_description'=>'Permisos eliminar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Usuarios index',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@index', 
		    	'permission_description'=>'Usuarios index',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Usuarios',
		    	'menu_module_icon'=>'fa-users',
		    	'menu_item'=>'Mostrar',
		    	'menu_item_route'=>'admin.users.index',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Usuarios crear',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@create', 
		    	'permission_description'=>'Usuarios crear',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Usuarios',
		    	'menu_module_icon'=>'fa-users',
		    	'menu_item'=>'Crear',
		    	'menu_item_route'=>'admin.users.create',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Usuarios guardar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@store', 
		    	'permission_description'=>'Usuarios guardar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Usuarios listar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@show', 
		    	'permission_description'=>'Usuarios listar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Usuarios editar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@edit', 
		    	'permission_description'=>'Usuarios editar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Usuarios actualizar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@update', 
		    	'permission_description'=>'Usuarios actualizar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Usuarios eliminar',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@destroy', 
		    	'permission_description'=>'Usuarios eliminar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
		    [
		    	'permission_title' => 'Clientes index',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ClienteController@index', 
		    	'permission_description'=>'Clientes index',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Clientes',
		    	'menu_module_icon'=>'fa-user',
		    	'menu_item'=>'Mostrar',
		    	'menu_item_route'=>'admin.clientes.index',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Clientes crear',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ClienteController@create', 
		    	'permission_description'=>'Clientes crear',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Clientes',
		    	'menu_module_icon'=>'fa-user',
		    	'menu_item'=>'Crear',
		    	'menu_item_route'=>'admin.clientes.create',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Clientes guardar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ClienteController@store', 
		    	'permission_description'=>'Clientes guardar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Clientes listar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ClienteController@show', 
		    	'permission_description'=>'Clientes listar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Clientes editar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ClienteController@edit', 
		    	'permission_description'=>'Clientes editar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Clientes actualizar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ClienteController@update', 
		    	'permission_description'=>'Clientes actualizar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Clientes eliminar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ClienteController@destroy', 
		    	'permission_description'=>'Clientes eliminar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Cargar Ciudades',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ClienteController@cargarCiudades', 
		    	'permission_description'=>'Cargar Ciudades',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
		    [
		    	'permission_title' => 'Productos index',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoController@index', 
		    	'permission_description'=>'Productos index',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Productos',
		    	'menu_module_icon'=>'fa-user',
		    	'menu_item'=>'Mostrar',
		    	'menu_item_route'=>'admin.productos.index',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos crear',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoController@create', 
		    	'permission_description'=>'Productos crear',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Productos',
		    	'menu_module_icon'=>'fa-user',
		    	'menu_item'=>'Crear',
		    	'menu_item_route'=>'admin.productos.create',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos guardar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoController@store', 
		    	'permission_description'=>'Productos guardar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos listar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoController@show', 
		    	'permission_description'=>'Productos listar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos editar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoController@edit', 
		    	'permission_description'=>'Productos editar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos actualizar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoController@update', 
		    	'permission_description'=>'Productos actualizar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos eliminar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoController@destroy', 
		    	'permission_description'=>'Productos eliminar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
		    [
		    	'permission_title' => 'Productos Categoria index',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoCatController@index', 
		    	'permission_description'=>'Productos Categoria index',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Productos',
		    	'menu_module_icon'=>'fa-user',
		    	'menu_item'=>'Mostrar Categorias',
		    	'menu_item_route'=>'admin.productosCat.index',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos Categoria crear',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoCatController@create', 
		    	'permission_description'=>'Productos Categoria crear',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Productos',
		    	'menu_module_icon'=>'fa-user',
		    	'menu_item'=>'Crear Categoria',
		    	'menu_item_route'=>'admin.productosCat.create',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos Categoria guardar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoCatController@store', 
		    	'permission_description'=>'Productos Categoria guardar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos Categoria listar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoCatController@show', 
		    	'permission_description'=>'Productos Categoria listar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos Categoria editar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoCatController@edit', 
		    	'permission_description'=>'Productos Categoria editar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos Categoria actualizar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoCatController@update', 
		    	'permission_description'=>'Productos Categoria actualizar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Productos Categoria eliminar',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\ProductoCatController@destroy', 
		    	'permission_description'=>'Productos Categoria eliminar',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
    	]);
    }
}
