<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
        	[
		    	'permission_title' => 'Dashboard',
		    	'permission_slug' => 'App\Http\Controllers\Admin\DashboardController@index',
		    	'permission_description'=>'Dashboard Page',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'View Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@index', 
		    	'permission_description'=>'View Profile',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@edit', 
		    	'permission_description'=>'Edit Profile',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Info Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@updateInfo', 
		    	'permission_description'=>'Update Info Profile',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Security Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@updateSecurity', 
		    	'permission_description'=>'Update Security Profile',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Avatar Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@editAvatar', 
		    	'permission_description'=>'Edit Avatar Profile',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Avatar Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@updateAvatar', 
		    	'permission_description'=>'Update Avatar Profile',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Confirm Email Profile',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\ProfileController@confirmEmailRegistration', 
		    	'permission_description'=>'Confirm Email Profile',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
		    [
		    	'permission_title' => 'Index Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@index', 
		    	'permission_description'=>'List all records',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Roles',
		    	'menu_module_icon'=>'fa-user',
		    	'menu_item'=>'Mostrar',
		    	'menu_item_route'=>'admin.roles.index',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Create Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@create', 
		    	'permission_description'=>'Create Roles',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Roles',
		    	'menu_module_icon'=>'fa-user',
		    	'menu_item'=>'Crear',
		    	'menu_item_route'=>'admin.roles.create',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Save Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@store', 
		    	'permission_description'=>'Save roles',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Show Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@show', 
		    	'permission_description'=>'Show roles',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@edit', 
		    	'permission_description'=>'Edit Roles',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@update', 
		    	'permission_description'=>'Update Roles',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Delete Roles',
		    	'permission_slug' => 'App\Http\Controllers\Admin\Auth\RoleController@destroy', 
		    	'permission_description'=>'Delete Roles',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Index Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@index', 
		    	'permission_description'=>'List all records',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Permisos',
		    	'menu_module_icon'=>'fa-lock',
		    	'menu_item'=>'Mostrar',
		    	'menu_item_route'=>'admin.permissions.index',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Create Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@create', 
		    	'permission_description'=>'Create Permissions',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Permisos',
		    	'menu_module_icon'=>'fa-lock',
		    	'menu_item'=>'Crear',
		    	'menu_item_route'=>'admin.permissions.create',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Save Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@store', 
		    	'permission_description'=>'Save Permissions',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Show Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@show', 
		    	'permission_description'=>'Show Permissions',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@edit', 
		    	'permission_description'=>'Edit Permissions',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@update', 
		    	'permission_description'=>'Update Permissions',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Delete Permissions',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\PermissionController@destroy', 
		    	'permission_description'=>'Delete Permissions',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Index Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@index', 
		    	'permission_description'=>'List all records',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Usuarios',
		    	'menu_module_icon'=>'fa-users',
		    	'menu_item'=>'Mostrar',
		    	'menu_item_route'=>'admin.users.index',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Create Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@create', 
		    	'permission_description'=>'Create Users',
		    	'menu_show'=>'1',
		    	'menu_module'=>'Usuarios',
		    	'menu_module_icon'=>'fa-users',
		    	'menu_item'=>'Crear',
		    	'menu_item_route'=>'admin.users.create',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Save Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@store', 
		    	'permission_description'=>'Save Users',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Show Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@show', 
		    	'permission_description'=>'Show Users',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Edit Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@edit', 
		    	'permission_description'=>'Edit Users',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Update Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@update', 
		    	'permission_description'=>'Update Users',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
	    	[
		    	'permission_title' => 'Delete Users',
		    	'permission_slug' => 'App\\Http\\Controllers\\Admin\\Auth\\UserController@destroy', 
		    	'permission_description'=>'Delete Users',
		    	'menu_show'=>'0',
		    	'menu_module'=>'',
		    	'menu_module_icon'=>'',
		    	'menu_item'=>'',
		    	'menu_item_route'=>'',
            	'created_at' => new \Carbon\Carbon(),
            	'updated_at' => new \Carbon\Carbon(),
	    	],
    	]);
    }
}
